AWSTemplateFormatVersion: 2010-09-09
Description: S3 multi region bucket creation
Parameters:
  Bucket:
    Type: String
    Default: "richard"
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join [ '-', [ !Ref "AWS::Region", !Ref "AWS::AccountId" , !Ref Bucket ] ] 
